/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoborra2;

import java.sql.Connection;
import Conexion.ConexionBD;
import static Conexion.ConexionBD.getConnection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rodol
 */
public class Ventana321 extends javax.swing.JFrame {

    ConexionBD conexion;
    private static int idSucursal;
    private static int idMesa;
    private static int estado;
    /**
     * Creates new form Ventana321
     */
    public Ventana321(int idSucursal, int idMesa) throws SQLException, InterruptedException {
        initComponents();
        conexion = new ConexionBD();
        this.idSucursal = idSucursal;
        this.idMesa = idMesa;
        consultaEstado();
        System.out.println(estado);
        apariencia();
    }
    
    private void apariencia() throws InterruptedException{
        switch (estado) {
            case 1:
            case 2:
            case 3:
                jLbl1.setText("Bienvenidos!");
                jBtn1.setText("Pedir");
                break;
            case 4:
            case 5:
                jLbl1.setText("Su comida se esta preparando");
                jBtn1.setVisible(false);
                esperarComidaLista();
                break;
            case 6:
            case 7:
            case 8:
                jLbl1.setText("Su comida ya esta lista");
                jBtn1.setText("Pagar");
                jBtn1.setVisible(true);
            default:
                break; 
        }
    }

    private void consultaEstado() throws SQLException{
        int vEstado = -1;
        try (Connection conn = getConnection()){
            String query = "SELECT estado from mesa where idMesa = ?;";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1,idMesa);
            ResultSet rs = ps.executeQuery();
            rs.next();
            vEstado = rs.getInt(1);
            System.out.println("1" + vEstado);
        } catch (SQLException ex){
            System.out.println("Error: " + ex);
        }
        this.estado =  vEstado;
    }
    
    public static void cambiarEstado(){
        String query = "";
        try (Connection conn = getConnection()){
            switch (estado){
                case 1:
                case 2:
                case 3:
                    query = "UPDATE mesa SET estado = 4 where idMesa = ?";
                    break;
                case 4:
                    query = "UPDATE mesa SET estado = 5 where idMesa = ?";
                    break;
                case 5:
                case 6:
                case 7:
                case 8:
                    query = "UPDATE mesa SET estado = 1 where idMesa = ?";
                default:
                    break;
            }
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1, idMesa);
            ps.executeUpdate();
        } catch (SQLException ex) {
            System.out.println("Error en cambiarEstado: " + ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLbl1 = new javax.swing.JLabel();
        jBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosLogo/CapturaIcono.JPG"))); // NOI18N
        jLabel3.setText("jLabel1");
        jLabel3.setMaximumSize(new java.awt.Dimension(149, 140));
        jLabel3.setMinimumSize(new java.awt.Dimension(149, 140));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosLogo/CapturaIcono.JPG"))); // NOI18N
        jLabel5.setText("jLabel1");
        jLabel5.setMaximumSize(new java.awt.Dimension(149, 140));
        jLabel5.setMinimumSize(new java.awt.Dimension(149, 140));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 17, 72));

        jLbl1.setFont(new java.awt.Font("Barlow ExtraLight", 2, 36)); // NOI18N
        jLbl1.setForeground(new java.awt.Color(85, 231, 255));
        jLbl1.setText(":");

        jBtn1.setBackground(new java.awt.Color(153, 204, 255));
        jBtn1.setFont(new java.awt.Font("Barlow Medium", 1, 18)); // NOI18N
        jBtn1.setForeground(new java.awt.Color(102, 0, 102));
        jBtn1.setText("Accion");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosLogo/CapturaIcono.JPG"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(149, 140));
        jLabel1.setMinimumSize(new java.awt.Dimension(149, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosLogo/CapturaIcono.JPG"))); // NOI18N
        jLabel2.setText("jLabel1");
        jLabel2.setMaximumSize(new java.awt.Dimension(149, 140));
        jLabel2.setMinimumSize(new java.awt.Dimension(149, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosLogo/CapturaIcono.JPG"))); // NOI18N
        jLabel4.setText("jLabel1");
        jLabel4.setMaximumSize(new java.awt.Dimension(149, 140));
        jLabel4.setMinimumSize(new java.awt.Dimension(149, 140));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RecursosLogo/CapturaIcono.JPG"))); // NOI18N
        jLabel6.setText("jLabel1");
        jLabel6.setMaximumSize(new java.awt.Dimension(149, 140));
        jLabel6.setMinimumSize(new java.awt.Dimension(149, 140));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(119, Short.MAX_VALUE)
                        .addComponent(jLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        try {
            cambiarEstado();
            switch (estado) {
                case 1:
                case 2:
                case 3:
                    new Ventana(idSucursal,idMesa).setVisible(true);
                    this.dispose();
                    break;
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                    try {
                        consultaEstado();
                    } catch (SQLException ex) {
                        System.out.println(ex);
                    }
                    apariencia();
                default:
                    break;
            }
            // TODO add your handling code here:
        } catch (InterruptedException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana321.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana321.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana321.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana321.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Ventana321(idSucursal, idMesa).setVisible(true);
                } catch (SQLException ex) {
                    System.out.println("Error: " + ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Ventana321.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    

    
    /**
     * Consulta el estado de la mesa cada 30 segundos para poder ver cuando este lista la comida
     * @throws InterruptedException 
     */
    private void esperarComidaLista() throws InterruptedException{
        //Crea el temporalizador para que se repita X instruccion (llamado tiempo)
        Timer tiempo = new Timer("ConsultaEstado");
        //Creacion del trabajo que se va a realizar repepitivamente (llamado validacion)
        TimerTask consulta = new TimerTask() {
            @Override
            public void run() {
                //Consulta el estado de la mesa
                try (Connection conn = getConnection()){
                    consultaEstado();
                } catch (SQLException ex){
                    System.out.println(ex);
                }
                //Si la mesa se encuentra en estado de comida lista
                if (estado == 6){
                    try {
                        System.out.println("Ya esta");
                        apariencia();
                        //Se termina el temporalizador y continua el proceso del restaurante
                        Thread.sleep(0);
                        tiempo.cancel();
                        
                    } catch (InterruptedException ex) {
                        System.out.println(ex);
                    }
                } else {
                    System.out.println("No esta listo");
                }
            }
        };
        //Se inicia el temporalizador y cada 30 segundos se realiza el proceso de consulta
        tiempo.scheduleAtFixedRate(consulta,0,30000L);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLbl1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
